import type { Metadata } from "next";
import { Inconsolata, Big_Shoulders, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/Header/Header";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const bigShoulders = Big_Shoulders({
  variable: "--font-big-shoulders",
  subsets: ["latin"],
});

const inconsolata = Inconsolata({
  variable: "--font-inconsolata",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "kusssomax",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", bigShoulders.variable, inconsolata.variable, "font-sans", inter.variable)}
    >
      <body>
        <Header />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
